### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by qasimalyas** [jakubpawlowicz/assets-packager#4]
I've been trying to follow the instructions to compile the example but I keep getting this error http://jsfiddle.net/TXpgt/embedded/js/

**Comment by GoalSmashers** [comment]
Hi Qasim,

It's quite interesting to see ruby stack trace after executing node.js code!
Can you ensure there's less dependency in your Gemfile (if you use bundler) and try it once again?

To be honest I use less.js all the time (npm install -g less) and it works fine that way. However it would be good to make it compliant with Ruby version too.

By the way it would be also interesting to learn why would you like to use assets-packager instead of Rails' built in assets pipeline. We actually use assets-packager exclusively for our node.js- and Sinatra-based applications.

Jakub Pawlowicz

**Comment by qasimalyas** [comment]
Ok so basically I had to remove the less gem file. That did trip me up so now it's working. I'm not sure if its worth adding this to your docs - just to help others. Thanks for your help, you've been awesome!

**Comment by jakubpawlowicz** [comment]
Sure, no problem! I think I'll add some notes on Ruby's less to the docs. 

Enjoy,
Jakub
